/** Shared hero sky layout profiles (viewBox 0–100 coords). */
export const HERO_SKY_DESKTOP = {
  id: 'desktop',
  starCount: 210,
  starSeed: 58219,
  yMax: 88,
  yDenseMax: 75,
  ySpawnMin: 0,
  ySpawnMax: 75,
  yDenseShare: 0.68,
  yDensePower: 0.72,
  yDenseSpan: 0.58,
  minSpacing: 1.65,
  glowShare: 0.14,
  sparkleShare: 0.12,
  constellationClearance: 1.5,
  constellationLineClearance: 0.55,
  constellationInteriorClearance: 0.85,
  starfieldClip: { x: 0, y: 0, width: 100, height: 88 },
  preserveAspectRatio: 'xMidYMid slice',
  constellation: {
    clip: { x: 44, y: 32, width: 56, height: 36 },
    tx: 54,
    ty: 30,
    scale: 1.65,
    starSizeScale: 1.5,
  },
}

export const HERO_SKY_TABLET = {
  id: 'tablet',
  starCount: 145,
  starSeed: 58219,
  yMax: 88,
  yDenseMax: 75,
  ySpawnMin: 0,
  ySpawnMax: 75,
  yDenseShare: 0.68,
  yDensePower: 0.72,
  yDenseSpan: 0.58,
  minSpacing: 1.8,
  glowShare: 0.12,
  sparkleShare: 0.05,
  sparkleGlowAllowed: false,
  sparkleArmMax: 0.42,
  sparkleGlowArmMax: 0.5,
  sparkleArmMaxPx: 5.5,
  constellationClearance: 2.8,
  constellationLineClearance: 1.15,
  constellationInteriorClearance: 1.5,
  constellationLineGlowPx: 7,
  starfieldClip: { x: 0, y: 0, width: 100, height: 88 },
  preserveAspectRatio: 'xMidYMid slice',
  constellationViewBox: { x: 35, y: 31, width: 32, height: 36 },
  constellation: {
    clip: { x: 35, y: 31, width: 32, height: 36 },
    tx: 37.9,
    ty: 33.5,
    scale: 1.38,
    starSizeScale: 1.45,
    starMinBoost: 1,
  },
}

export const HERO_SKY_MOBILE = {
  id: 'mobile',
  starCount: 95,
  starSeed: 58219,
  yMax: 99,
  ySpawnMin: 0,
  ySpawnMax: 92,
  yDenseShare: 0.66,
  yDensePower: 0.92,
  yDenseSpan: 0.62,
  minSpacing: 2.45,
  constellationClearance: 3.2,
  constellationLineClearance: 1.25,
  constellationInteriorClearance: 1.6,
  constellationLineGlowPx: 7,
  starfieldSizeScale: 0.561,
  glowShare: 0.08,
  sparkleShare: 0.05,
  starfieldClip: { x: 0, y: 0, width: 100, height: 99 },
  preserveAspectRatio: 'xMidYMid slice',
  constellationViewBox: { x: 35, y: 31, width: 32, height: 36 },
  constellation: {
    clip: { x: 35, y: 31, width: 32, height: 36 },
    tx: 37.9,
    ty: 33.5,
    scale: 1.28,
    starSizeScale: 1.5,
    starMinBoost: 1,
  },
}

export function getHeroSkyLayout(viewportWidth) {
  if (viewportWidth <= 480) return HERO_SKY_MOBILE
  if (viewportWidth <= 920) return HERO_SKY_TABLET
  return HERO_SKY_DESKTOP
}
